#include "CppExporter.h"

#include "CodeAnalyser/CodeAnalyser.h"
#include "CodeAnalyser/FunctionAnalyser.h"
#include "Misc/EmuBase.h"

#include <stdio.h>

// =====================================================================================
// Tier-A C++ recompiler backend (SKELETON). See CppExporter.h header comment.
//
// Control-flow model: one big translation function per program, basic blocks emitted as
// goto-labelled sections in address order. This handles overlapping / fall-through entry
// points (e.g. AddAToHL* at $AEE3/4/5) for free, because every entry is just a label.
// =====================================================================================

// -------------------------------------------------------------------------------------
// Naming helpers
// -------------------------------------------------------------------------------------

std::string FCppExporter::BlockLabel(FAddressRef addr) const
{
	char buf[32];
	snprintf(buf, sizeof(buf), "L_%04X", addr.Address);
	return buf;
}

std::string FCppExporter::FunctionName(FAddressRef addr) const
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FLabelInfo* pLabel = state.GetLabelForAddress(addr);
	if (pLabel != nullptr && pLabel->GetName()[0] != '\0')
		return pLabel->GetName();

	char buf[32];
	snprintf(buf, sizeof(buf), "func_%04X", addr.Address);
	return buf;
}

std::string FCppExporter::DisassemblyText(FAddressRef addr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FCodeInfo* pCodeInfo = state.GetCodeInfoForAddress(addr);
	if (pCodeInfo != nullptr && pCodeInfo->Text.empty() == false)
		return pCodeInfo->Text;	// stored disassembly; good enough for a provenance comment
	return "<no disassembly>";
}

// -------------------------------------------------------------------------------------
// Runtime preamble (header)
// -------------------------------------------------------------------------------------

void FCppExporter::EmitCpuStateStruct(void)
{
	const bool bC = RecompilerConfig.bEmitC;
	Output("// ---- CPU state ---------------------------------------------------------\n");
	Output(bC ? "typedef struct\n{\n" : "struct Z80CpuState\n{\n");
	Output("\tuint8_t  A, F, B, C, D, E, H, L;\n");
	Output("\tuint8_t  A_, F_, B_, C_, D_, E_, H_, L_;   // shadow registers\n");
	Output("\tuint16_t IX, IY, SP, PC;\n");
	Output("\tuint8_t  I, R;\n");
	Output("\tbool     IFF1, IFF2;\n");
	Output("\tuint8_t  IM;\n");
	Output("\tbool     Halted;\n");
	Output("\tuint64_t Cycles;          // for timing-sensitive code / IRQ gating\n");
	Output("\tuint8_t* Mem;             // 64K (or paging-window) byte array, AUTHORITATIVE\n");
	Output(bC ? "} Z80CpuState;\n\n" : "};\n\n");
}

void FCppExporter::EmitRuntimeDeclarations(void)
{
	// Hooks (and the inline helpers) always take a Z80CpuState* so generated code can call
	// them uniformly via CpuPtr() in both targets. Only the generated function *signatures*
	// (Program/entry points) use the reference form in C++ - that boundary is the harness's.
	const char* pCpu = "Z80CpuState* cpu";
	Output("// ---- Runtime hooks (provided by the harness) ---------------------------\n");
	Output("// Memory is the authoritative source of truth so that self-modifying code,\n");
	Output("// banking and I/O all remain interception points rather than special cases.\n");
	Output("uint8_t  Read8 (%s, uint16_t addr);\n", pCpu);
	Output("void     Write8(%s, uint16_t addr, uint8_t val);\n", pCpu);
	Output("uint8_t  In    (%s, uint16_t port);\n", pCpu);
	Output("void     Out   (%s, uint16_t port, uint8_t val);\n\n", pCpu);
	// Control flow is internal in the PC-dispatch model (see EmitDispatcher) - no
	// Call/JumpTo/DispatchIndirect hooks are needed.
}

void FCppExporter::EmitEntryPointDeclarations(void)
{
	Output("// ---- Entry points (run via z80_call(cpu, addr)) ------------------------\n");
	for (const FAddressRef& entry : CFG.EntryPoints)
		Output("//   0x%04X  %s\n", entry.Address, FunctionName(entry).c_str());
	Output("\n");
}

void FCppExporter::AddHeader(void)
{
	Output("// Machine-generated by 8BitAnalysers FCppExporter (Tier A - faithful translation).\n");
	Output("// Target: %s. DO NOT EDIT: regenerate from the analysis project instead.\n\n",
		RecompilerConfig.bEmitC ? "C99" : "C++");
	if (RecompilerConfig.bEmitC)
		Output("#include <stdint.h>\n#include <stdbool.h>\n\n");
	else
		Output("#include <cstdint>\n\n");
	EmitCpuStateStruct();
	EmitRuntimeDeclarations();	// hook declarations first...
	EmitRuntimeHelpers();		// ...so the inline helpers (push16/pop16) can call them
	// Entry-point list depends on the CFG, which is built in ExportProgram.
}

// Inline Z80 flag/ALU primitives. These are transcribed from the chips Z80 core
// (Source/Vendor/chips/chips/z80.h) so generated code is bit-accurate against the
// emulator used for differential validation. Identical text in C and C++.
void FCppExporter::EmitRuntimeHelpers(void)
{
	Output("// ---- Z80 flag/ALU runtime (mirrors Vendor/chips/chips/z80.h) -----------\n");
	Output("enum { Z80_CF=1<<0, Z80_NF=1<<1, Z80_VF=1<<2, Z80_PF=Z80_VF,\n");
	Output("       Z80_XF=1<<3, Z80_HF=1<<4, Z80_YF=1<<5, Z80_ZF=1<<6, Z80_SF=1<<7 };\n\n");

	Output("static inline uint8_t z80_sz(uint8_t v){ return (v!=0)?(v&Z80_SF):Z80_ZF; }\n");
	Output("static inline uint8_t z80_szp(uint8_t v){\n");
	Output("\tuint8_t p=v; p^=p>>4; p^=p>>2; p^=p>>1;\n");
	Output("\treturn z80_sz(v) | (v&(Z80_YF|Z80_XF)) | ((p&1)?0:Z80_PF);\n}\n");
	Output("static inline uint8_t z80_szyxch(uint8_t a,uint8_t v,uint32_t r){\n");
	Output("\treturn z80_sz((uint8_t)r)|(r&(Z80_YF|Z80_XF))|((r>>8)&Z80_CF)|((a^v^r)&Z80_HF);\n}\n");
	Output("static inline uint8_t z80_addf(uint8_t a,uint8_t v,uint32_t r){\n");
	Output("\treturn z80_szyxch(a,v,r)|((((v^a^0x80)&(v^r))>>5)&Z80_VF);\n}\n");
	Output("static inline uint8_t z80_subf(uint8_t a,uint8_t v,uint32_t r){\n");
	Output("\treturn Z80_NF|z80_szyxch(a,v,r)|((((v^a)&(r^a))>>5)&Z80_VF);\n}\n");
	Output("static inline uint8_t z80_cpf(uint8_t a,uint8_t v,uint32_t r){\n");
	Output("\treturn Z80_NF|z80_sz((uint8_t)r)|(v&(Z80_YF|Z80_XF))|((r>>8)&Z80_CF)|((a^v^r)&Z80_HF)|((((v^a)&(r^a))>>5)&Z80_VF);\n}\n\n");

	Output("static inline void z80_add8(Z80CpuState* c,uint8_t v){ uint32_t r=c->A+v;            c->F=z80_addf(c->A,v,r); c->A=(uint8_t)r; }\n");
	Output("static inline void z80_adc8(Z80CpuState* c,uint8_t v){ uint32_t r=c->A+v+(c->F&Z80_CF); c->F=z80_addf(c->A,v,r); c->A=(uint8_t)r; }\n");
	Output("static inline void z80_sub8(Z80CpuState* c,uint8_t v){ uint32_t r=(uint32_t)((int)c->A-(int)v);              c->F=z80_subf(c->A,v,r); c->A=(uint8_t)r; }\n");
	Output("static inline void z80_sbc8(Z80CpuState* c,uint8_t v){ uint32_t r=(uint32_t)((int)c->A-(int)v-(c->F&Z80_CF));c->F=z80_subf(c->A,v,r); c->A=(uint8_t)r; }\n");
	Output("static inline void z80_and8(Z80CpuState* c,uint8_t v){ c->A&=v; c->F=z80_szp(c->A)|Z80_HF; }\n");
	Output("static inline void z80_xor8(Z80CpuState* c,uint8_t v){ c->A^=v; c->F=z80_szp(c->A); }\n");
	Output("static inline void z80_or8 (Z80CpuState* c,uint8_t v){ c->A|=v; c->F=z80_szp(c->A); }\n");
	Output("static inline void z80_cp8 (Z80CpuState* c,uint8_t v){ uint32_t r=(uint32_t)((int)c->A-(int)v); c->F=z80_cpf(c->A,v,r); }\n");
	Output("static inline uint8_t z80_inc8(Z80CpuState* c,uint8_t v){ uint8_t r=v+1; uint8_t f=z80_sz(r)|(r&(Z80_XF|Z80_YF))|((r^v)&Z80_HF); if(r==0x80)f|=Z80_VF; c->F=f|(c->F&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_dec8(Z80CpuState* c,uint8_t v){ uint8_t r=v-1; uint8_t f=Z80_NF|z80_sz(r)|(r&(Z80_XF|Z80_YF))|((r^v)&Z80_HF); if(r==0x7F)f|=Z80_VF; c->F=f|(c->F&Z80_CF); return r; }\n\n");

	// 16-bit register-pair accessors.
	Output("static inline uint16_t z80_bc(Z80CpuState* c){ return (uint16_t)((c->B<<8)|c->C); }\n");
	Output("static inline uint16_t z80_de(Z80CpuState* c){ return (uint16_t)((c->D<<8)|c->E); }\n");
	Output("static inline uint16_t z80_hl(Z80CpuState* c){ return (uint16_t)((c->H<<8)|c->L); }\n");
	Output("static inline uint16_t z80_af(Z80CpuState* c){ return (uint16_t)((c->A<<8)|c->F); }\n");
	Output("static inline void z80_set_bc(Z80CpuState* c,uint16_t v){ c->B=(uint8_t)(v>>8); c->C=(uint8_t)v; }\n");
	Output("static inline void z80_set_de(Z80CpuState* c,uint16_t v){ c->D=(uint8_t)(v>>8); c->E=(uint8_t)v; }\n");
	Output("static inline void z80_set_hl(Z80CpuState* c,uint16_t v){ c->H=(uint8_t)(v>>8); c->L=(uint8_t)v; }\n");
	Output("static inline void z80_set_af(Z80CpuState* c,uint16_t v){ c->A=(uint8_t)(v>>8); c->F=(uint8_t)v; }\n\n");

	Output("static inline void z80_add16(Z80CpuState* c,uint16_t val){ uint16_t acc=z80_hl(c); uint32_t res=acc+val;\n");
	Output("\tc->F=(c->F&(Z80_SF|Z80_ZF|Z80_VF))|(((acc^res^val)>>8)&Z80_HF)|((res>>16)&Z80_CF)|((res>>8)&(Z80_YF|Z80_XF)); z80_set_hl(c,(uint16_t)res); }\n\n");

	// Accumulator rotates (RLCA/RRCA/RLA/RRA).
	Output("static inline void z80_rlca(Z80CpuState* c){ uint8_t r=(uint8_t)((c->A<<1)|(c->A>>7)); c->F=((c->A>>7)&Z80_CF)|(c->F&(Z80_SF|Z80_ZF|Z80_PF))|(r&(Z80_YF|Z80_XF)); c->A=r; }\n");
	Output("static inline void z80_rrca(Z80CpuState* c){ uint8_t r=(uint8_t)((c->A>>1)|(c->A<<7)); c->F=(c->A&Z80_CF)|(c->F&(Z80_SF|Z80_ZF|Z80_PF))|(r&(Z80_YF|Z80_XF)); c->A=r; }\n");
	Output("static inline void z80_rla(Z80CpuState* c){ uint8_t r=(uint8_t)((c->A<<1)|(c->F&Z80_CF)); c->F=((c->A>>7)&Z80_CF)|(c->F&(Z80_SF|Z80_ZF|Z80_PF))|(r&(Z80_YF|Z80_XF)); c->A=r; }\n");
	Output("static inline void z80_rra(Z80CpuState* c){ uint8_t r=(uint8_t)((c->A>>1)|((c->F&Z80_CF)<<7)); c->F=(c->A&Z80_CF)|(c->F&(Z80_SF|Z80_ZF|Z80_PF))|(r&(Z80_YF|Z80_XF)); c->A=r; }\n\n");

	// DAA / CPL / SCF / CCF.
	Output("static inline void z80_daa(Z80CpuState* c){ uint8_t r=c->A;\n");
	Output("\tif(c->F&Z80_NF){ if(((c->A&0xF)>0x9)||(c->F&Z80_HF))r-=0x06; if((c->A>0x99)||(c->F&Z80_CF))r-=0x60; }\n");
	Output("\telse          { if(((c->A&0xF)>0x9)||(c->F&Z80_HF))r+=0x06; if((c->A>0x99)||(c->F&Z80_CF))r+=0x60; }\n");
	Output("\tc->F&=Z80_CF|Z80_NF; c->F|=(c->A>0x99)?Z80_CF:0; c->F|=(c->A^r)&Z80_HF; c->F|=z80_szp(r); c->A=r; }\n");
	Output("static inline void z80_cpl(Z80CpuState* c){ c->A^=0xFF; c->F=(c->F&(Z80_SF|Z80_ZF|Z80_PF|Z80_CF))|Z80_HF|Z80_NF|(c->A&(Z80_YF|Z80_XF)); }\n");
	Output("static inline void z80_scf(Z80CpuState* c){ c->F=(c->F&(Z80_SF|Z80_ZF|Z80_PF|Z80_CF))|Z80_CF|(c->A&(Z80_YF|Z80_XF)); }\n");
	Output("static inline void z80_ccf(Z80CpuState* c){ c->F=((c->F&(Z80_SF|Z80_ZF|Z80_PF|Z80_CF))|((c->F&Z80_CF)<<4)|(c->A&(Z80_YF|Z80_XF)))^Z80_CF; }\n\n");

	// Register exchanges.
	Output("static inline void z80_ex_de_hl(Z80CpuState* c){ uint16_t t=z80_de(c); z80_set_de(c,z80_hl(c)); z80_set_hl(c,t); }\n");
	Output("static inline void z80_ex_af(Z80CpuState* c){ uint8_t t; t=c->A;c->A=c->A_;c->A_=t; t=c->F;c->F=c->F_;c->F_=t; }\n");
	Output("static inline void z80_exx(Z80CpuState* c){ uint8_t t;\n");
	Output("\tt=c->B;c->B=c->B_;c->B_=t; t=c->C;c->C=c->C_;c->C_=t; t=c->D;c->D=c->D_;c->D_=t;\n");
	Output("\tt=c->E;c->E=c->E_;c->E_=t; t=c->H;c->H=c->H_;c->H_=t; t=c->L;c->L=c->L_;c->L_=t; }\n\n");

	// CB-page rotates/shifts (return result, set S/Z/P/X/Y from result and CF from the
	// shifted-out bit) and BIT (test only - no writeback).
	Output("static inline uint8_t z80_rlc(Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)((v<<1)|(v>>7)); c->F=z80_szp(r)|((v>>7)&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_rrc(Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)((v>>1)|(v<<7)); c->F=z80_szp(r)|(v&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_rl (Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)((v<<1)|(c->F&Z80_CF)); c->F=z80_szp(r)|((v>>7)&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_rr (Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)((v>>1)|((c->F&Z80_CF)<<7)); c->F=z80_szp(r)|(v&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_sla(Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)(v<<1); c->F=z80_szp(r)|((v>>7)&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_sra(Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)((v>>1)|(v&0x80)); c->F=z80_szp(r)|(v&Z80_CF); return r; }\n");
	Output("static inline uint8_t z80_sll(Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)((v<<1)|1); c->F=z80_szp(r)|((v>>7)&Z80_CF); return r; }\n");	// undocumented
	Output("static inline uint8_t z80_srl(Z80CpuState* c,uint8_t v){ uint8_t r=(uint8_t)(v>>1); c->F=z80_szp(r)|(v&Z80_CF); return r; }\n");
	// NOTE: for BIT n,(HL) the real Z80 takes the X/Y flags from the internal WZ register;
	// we use the operand value instead (correct for register operands; minor (HL) inaccuracy
	// pending WZ modelling).
	Output("static inline void z80_bit(Z80CpuState* c,uint8_t v,int n){ uint8_t r=(uint8_t)(v&(1<<n)); c->F=(c->F&Z80_CF)|Z80_HF|(r?(r&Z80_SF):(Z80_ZF|Z80_PF))|(v&(Z80_YF|Z80_XF)); }\n\n");

	// 16-bit stack push/pop (used by CALL/RET and PUSH/POP); go through the memory hooks.
	Output("static inline void z80_push16(Z80CpuState* c,uint16_t v){ c->SP-=2; Write8(c,(uint16_t)(c->SP+1),(uint8_t)(v>>8)); Write8(c,c->SP,(uint8_t)v); }\n");
	Output("static inline uint16_t z80_pop16(Z80CpuState* c){ uint8_t lo=Read8(c,c->SP), hi=Read8(c,(uint16_t)(c->SP+1)); c->SP+=2; return (uint16_t)((hi<<8)|lo); }\n\n");

	// ---- ED-page helpers (transcribed from Vendor/chips/chips/z80.h) -----------
	// NEG: A = -A; flag computation matches the SUB path.
	Output("static inline void z80_neg(Z80CpuState* c){ uint32_t r=(uint32_t)(0-(int)c->A); c->F=z80_subf(0,c->A,r); c->A=(uint8_t)r; }\n");

	// ADC HL,ss / SBC HL,ss - 16-bit. Flag formula is bespoke (V from sign-bit overflow,
	// H from bit-12 carry, Z from full 16-bit result). Matches _z80_adc16 / _z80_sbc16.
	Output("static inline void z80_adc16(Z80CpuState* c,uint16_t val){ uint16_t acc=z80_hl(c); uint32_t r=acc+val+(c->F&Z80_CF);\n");
	Output("\tc->F=(uint8_t)((((val^acc^0x8000)&(val^r)&0x8000)>>13) | (((acc^r^val)>>8)&Z80_HF) | ((r>>16)&Z80_CF) | ((r>>8)&(Z80_SF|Z80_YF|Z80_XF)) | ((r&0xFFFF)?0:Z80_ZF));\n");
	Output("\tz80_set_hl(c,(uint16_t)r); }\n");
	Output("static inline void z80_sbc16(Z80CpuState* c,uint16_t val){ uint16_t acc=z80_hl(c); uint32_t r=acc-val-(c->F&Z80_CF);\n");
	Output("\tc->F=(uint8_t)(Z80_NF | (((val^acc)&(acc^r)&0x8000)>>13) | (((acc^r^val)>>8)&Z80_HF) | ((r>>16)&Z80_CF) | ((r>>8)&(Z80_SF|Z80_YF|Z80_XF)) | ((r&0xFFFF)?0:Z80_ZF));\n");
	Output("\tz80_set_hl(c,(uint16_t)r); }\n\n");

	// Block-op helpers. Each updates flags + BC (LDI/LDD/CPI/CPD) or B (INI/IND/OUTI/OUTD)
	// and returns whether the repeating variant should iterate again. HL/DE pointer arithmetic
	// is emitted at the call site so the same helper serves both increment and decrement.
	Output("static inline bool z80_ldi_ldd(Z80CpuState* c,uint8_t val){ uint8_t r=c->A+val; uint16_t bc=z80_bc(c)-1; z80_set_bc(c,bc);\n");
	Output("\tc->F=(c->F&(Z80_SF|Z80_ZF|Z80_CF))|((r&2)?Z80_YF:0)|((r&8)?Z80_XF:0)|(bc?Z80_PF:0); return bc!=0; }\n");
	Output("static inline bool z80_cpi_cpd(Z80CpuState* c,uint8_t val){ uint32_t r=(uint32_t)((int)c->A-(int)val); uint16_t bc=z80_bc(c)-1; z80_set_bc(c,bc);\n");
	Output("\tuint8_t f=(c->F&Z80_CF)|Z80_NF|z80_sz((uint8_t)r);\n");
	Output("\tif((r&0xF) > ((uint32_t)c->A&0xF)){ f|=Z80_HF; r--; }\n");
	Output("\tif(r&2) f|=Z80_YF; if(r&8) f|=Z80_XF; if(bc) f|=Z80_PF; c->F=f; return (bc!=0) && !(f&Z80_ZF); }\n");
	Output("static inline bool z80_ini_ind(Z80CpuState* c,uint8_t val,uint8_t cc){ uint8_t b=c->B; uint8_t f=z80_sz(b)|(b&(Z80_XF|Z80_YF));\n");
	Output("\tif(val&Z80_SF) f|=Z80_NF; uint32_t t=(uint32_t)cc+val; if(t&0x100) f|=Z80_HF|Z80_CF;\n");
	Output("\tuint8_t p=(uint8_t)((t&7)^b); p^=p>>4; p^=p>>2; p^=p>>1; if(!(p&1)) f|=Z80_PF; c->F=f; return b!=0; }\n");
	Output("static inline bool z80_outi_outd(Z80CpuState* c,uint8_t val){ uint8_t b=c->B; uint8_t f=z80_sz(b)|(b&(Z80_XF|Z80_YF));\n");
	Output("\tif(val&Z80_SF) f|=Z80_NF; uint32_t t=(uint32_t)c->L+val; if(t&0x100) f|=Z80_HF|Z80_CF;\n");
	Output("\tuint8_t p=(uint8_t)((t&7)^b); p^=p>>4; p^=p>>2; p^=p>>1; if(!(p&1)) f|=Z80_PF; c->F=f; return b!=0; }\n\n");

	// IN r,(C) flag side-effect: szp on the read byte, CF preserved.
	Output("static inline uint8_t z80_in_flags(Z80CpuState* c,uint8_t val){ c->F=(c->F&Z80_CF)|z80_szp(val); return val; }\n");

	// RRD / RLD - 4-bit rotate involving (HL) and A's low nibble. Flag formula: szp(A), CF preserved.
	Output("static inline uint8_t z80_rrd(Z80CpuState* c,uint8_t val){ uint8_t alo=c->A&0x0F; c->A=(uint8_t)((c->A&0xF0)|(val&0x0F)); uint8_t v=(uint8_t)((val>>4)|(alo<<4)); c->F=(c->F&Z80_CF)|z80_szp(c->A); return v; }\n");
	Output("static inline uint8_t z80_rld(Z80CpuState* c,uint8_t val){ uint8_t alo=c->A&0x0F; c->A=(uint8_t)((c->A&0xF0)|(val>>4)); uint8_t v=(uint8_t)((val<<4)|alo); c->F=(c->F&Z80_CF)|z80_szp(c->A); return v; }\n\n");
}

// -------------------------------------------------------------------------------------
// Instruction & block emission
// -------------------------------------------------------------------------------------

void FCppExporter::EmitInstruction(FAddressRef addr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FInstructionFlow flow = ClassifyInstruction(state, addr);

	// Provenance comment - always emitted so the generated code stays auditable.
	Output("\t// %04X: %s\n", addr.Address, DisassemblyText(addr).c_str());

	// Control-flow instructions (JP/JR/CALL/RET/DJNZ/RST/HALT/JP(HL)) carry no inline data
	// semantics - their transfer is emitted by EmitTerminator. Keyed off the instruction's
	// own classification, NOT "is it the block's last instruction": a block that ends by
	// fall-through (next address is a leader) still needs its final instruction's semantics.
	if (flow.bEndsBlock)
		return;

	if (state.CPUInterface->CPUType == ECPUType::Z80)
		EmitInstructionSemanticsZ80(addr);
	else
		Output("\t/* TODO(Phase 1): semantics (non-Z80 CPU) */\n");
}

// Phase 1: the main (unprefixed) Z80 opcode page. Covers NOP; 8-bit loads (LD r,r'/r,n,
// (HL) forms); 8-bit ALU A,r/A,n; INC/DEC r; 16-bit LD dd,nn, INC/DEC ss, ADD HL,ss;
// A/HL <-> memory loads (LD (BC)/(DE)/(nn) etc.); PUSH/POP; accumulator rotates and
// DAA/CPL/SCF/CCF; EX/EXX; LD SP,HL; IN/OUT (n); DI/EI; and the full CB page (rotates/
// shifts, BIT/RES/SET, including (HL) forms). Decoded via the regular octal opcode
// structure (x/y/z/p/q fields, see z80.info/decoding.htm). The DD/FD (IX/IY) and ED
// prefixes are NOT yet handled and fall back to a clearly-marked TODO.
void FCppExporter::EmitInstructionSemanticsZ80(FAddressRef addr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const uint8_t op = state.ReadByte(addr);
	const int x = op >> 6, y = (op >> 3) & 7, z = op & 7;
	const int p = y >> 1, q = y & 1;	// register-pair / flag-group sub-fields

	static const char* kRegName[8] = { "B", "C", "D", "E", "H", "L", "(HL)", "A" };
	static const char* kAlu[8]     = { "z80_add8", "z80_adc8", "z80_sub8", "z80_sbc8",
	                                    "z80_and8", "z80_xor8", "z80_or8",  "z80_cp8" };
	const char* acc = Acc();

	// Read expression for register/(HL) operand index r (0..7).
	auto regRead = [&](int r) -> std::string
	{
		if (r == 6)	// (HL)
		{
			char buf[64];
			snprintf(buf, sizeof(buf), "Read8(%s, (%sH<<8)|%sL)", CpuPtr(), acc, acc);
			return buf;
		}
		return std::string(acc) + kRegName[r];
	};

	// 16-bit register-pair read expression for index pp (0..3 = BC,DE,HL,SP).
	auto rpRead = [&](int pp) -> std::string
	{
		char buf[48];
		if (pp == 3) { snprintf(buf, sizeof(buf), "%sSP", acc); return buf; }
		static const char* nm[3] = { "bc", "de", "hl" };
		snprintf(buf, sizeof(buf), "z80_%s(%s)", nm[pp], CpuPtr());
		return buf;
	};
	// Emit an assignment of valExpr to register-pair pp.
	auto rpWrite = [&](int pp, const std::string& valExpr)
	{
		if (pp == 3) { Output("\t%sSP = %s;\n", acc, valExpr.c_str()); return; }
		static const char* nm[3] = { "bc", "de", "hl" };
		Output("\tz80_set_%s(%s, %s);\n", nm[pp], CpuPtr(), valExpr.c_str());
	};

	if (op == 0x00) { Output("\t/* NOP */\n"); return; }

	if (op == 0xCB)	// CB prefix: the real opcode is the second byte (its own x/y/z are moot)
	{
		const uint8_t cb = state.ReadByte(addr.Address + 1);
		const int cx = cb >> 6, cy = (cb >> 3) & 7, cz = cb & 7;
		const bool bHL = (cz == 6);
		static const char* kRot[8] = { "z80_rlc","z80_rrc","z80_rl","z80_rr",
		                               "z80_sla","z80_sra","z80_sll","z80_srl" };
		switch (cx)
		{
		case 0:	// rotate / shift (writes result back)
			if (bHL)
				Output("\tWrite8(%s, (%sH<<8)|%sL, %s(%s, Read8(%s, (%sH<<8)|%sL)));\n",
					CpuPtr(), acc, acc, kRot[cy], CpuPtr(), CpuPtr(), acc, acc);
			else
				Output("\t%s%s = %s(%s, %s%s);\n", acc, kRegName[cz], kRot[cy], CpuPtr(), acc, kRegName[cz]);
			return;
		case 1:	// BIT n,r (flags only, no writeback)
			if (bHL)
				Output("\tz80_bit(%s, Read8(%s, (%sH<<8)|%sL), %d);\n", CpuPtr(), CpuPtr(), acc, acc, cy);
			else
				Output("\tz80_bit(%s, %s%s, %d);\n", CpuPtr(), acc, kRegName[cz], cy);
			return;
		case 2:	// RES n,r (no flags)
		{
			const uint8_t mask = (uint8_t)(0xFF & ~(1 << cy));
			if (bHL)
				Output("\tWrite8(%s, (%sH<<8)|%sL, (uint8_t)(Read8(%s, (%sH<<8)|%sL) & 0x%02X));\n",
					CpuPtr(), acc, acc, CpuPtr(), acc, acc, mask);
			else
				Output("\t%s%s &= 0x%02X;\n", acc, kRegName[cz], mask);
			return;
		}
		case 3:	// SET n,r (no flags)
		{
			const uint8_t bit = (uint8_t)(1 << cy);
			if (bHL)
				Output("\tWrite8(%s, (%sH<<8)|%sL, (uint8_t)(Read8(%s, (%sH<<8)|%sL) | 0x%02X));\n",
					CpuPtr(), acc, acc, CpuPtr(), acc, acc, bit);
			else
				Output("\t%s%s |= 0x%02X;\n", acc, kRegName[cz], bit);
			return;
		}
		}
	}

	if (x == 1)	// LD r[y], r[z]   (0x76 HALT is a terminator, never reaches here)
	{
		const std::string src = regRead(z);
		if (y == 6)	// LD (HL), r
			Output("\tWrite8(%s, (%sH<<8)|%sL, %s);\n", CpuPtr(), acc, acc, src.c_str());
		else
			Output("\t%s%s = %s;\n", acc, kRegName[y], src.c_str());
		return;
	}

	if (x == 2)	// ALU[y] A, r[z]
	{
		Output("\t%s(%s, %s);\n", kAlu[y], CpuPtr(), regRead(z).c_str());
		return;
	}

	if (x == 3 && z == 6)	// ALU[y] A, n   (0xC6/0xCE/0xD6/.../0xFE)
	{
		const uint8_t n = state.ReadByte(addr.Address + 1);
		Output("\t%s(%s, 0x%02X);\n", kAlu[y], CpuPtr(), n);
		return;
	}

	if (x == 0)
	{
		if (z == 4)	// INC r[y]
		{
			if (y == 6)
				Output("\tWrite8(%s, (%sH<<8)|%sL, z80_inc8(%s, Read8(%s, (%sH<<8)|%sL)));\n",
					CpuPtr(), acc, acc, CpuPtr(), CpuPtr(), acc, acc);
			else
				Output("\t%s%s = z80_inc8(%s, %s%s);\n", acc, kRegName[y], CpuPtr(), acc, kRegName[y]);
			return;
		}
		if (z == 5)	// DEC r[y]
		{
			if (y == 6)
				Output("\tWrite8(%s, (%sH<<8)|%sL, z80_dec8(%s, Read8(%s, (%sH<<8)|%sL)));\n",
					CpuPtr(), acc, acc, CpuPtr(), CpuPtr(), acc, acc);
			else
				Output("\t%s%s = z80_dec8(%s, %s%s);\n", acc, kRegName[y], CpuPtr(), acc, kRegName[y]);
			return;
		}
		if (z == 6)	// LD r[y], n
		{
			const uint8_t n = state.ReadByte(addr.Address + 1);
			if (y == 6)
				Output("\tWrite8(%s, (%sH<<8)|%sL, 0x%02X);\n", CpuPtr(), acc, acc, n);
			else
				Output("\t%s%s = 0x%02X;\n", acc, kRegName[y], n);
			return;
		}
		if (z == 1 && q == 0)	// LD dd,nn
		{
			char nbuf[16];
			snprintf(nbuf, sizeof(nbuf), "0x%04X", state.ReadWord(addr.Address + 1));
			rpWrite(p, nbuf);
			return;
		}
		if (z == 1 && q == 1)	// ADD HL,ss
		{
			Output("\tz80_add16(%s, %s);\n", CpuPtr(), rpRead(p).c_str());
			return;
		}
		if (z == 3)	// INC ss (q==0) / DEC ss (q==1) - 16-bit, no flags
		{
			rpWrite(p, rpRead(p) + (q == 0 ? " + 1" : " - 1"));
			return;
		}
		if (z == 7)	// RLCA / RRCA / RLA / RRA / DAA / CPL / SCF / CCF
		{
			static const char* kAccOp[8] = { "z80_rlca","z80_rrca","z80_rla","z80_rra",
			                                  "z80_daa","z80_cpl","z80_scf","z80_ccf" };
			Output("\t%s(%s);\n", kAccOp[y], CpuPtr());
			return;
		}
		if (op == 0x08) { Output("\tz80_ex_af(%s);\n", CpuPtr()); return; }	// EX AF,AF'
		if (z == 2)	// indirect loads/stores between A/HL and memory
		{
			const uint16_t nn = state.ReadWord(addr.Address + 1);
			const uint16_t nn1 = (uint16_t)(nn + 1);
			switch (op)
			{
			case 0x02: Output("\tWrite8(%s, z80_bc(%s), %sA);\n", CpuPtr(), CpuPtr(), acc); return;	// LD (BC),A
			case 0x12: Output("\tWrite8(%s, z80_de(%s), %sA);\n", CpuPtr(), CpuPtr(), acc); return;	// LD (DE),A
			case 0x0A: Output("\t%sA = Read8(%s, z80_bc(%s));\n", acc, CpuPtr(), CpuPtr()); return;	// LD A,(BC)
			case 0x1A: Output("\t%sA = Read8(%s, z80_de(%s));\n", acc, CpuPtr(), CpuPtr()); return;	// LD A,(DE)
			case 0x22: Output("\tWrite8(%s, 0x%04X, %sL); Write8(%s, 0x%04X, %sH);\n", CpuPtr(), nn, acc, CpuPtr(), nn1, acc); return;	// LD (nn),HL
			case 0x2A: Output("\t%sL = Read8(%s, 0x%04X); %sH = Read8(%s, 0x%04X);\n", acc, CpuPtr(), nn, acc, CpuPtr(), nn1); return;	// LD HL,(nn)
			case 0x32: Output("\tWrite8(%s, 0x%04X, %sA);\n", CpuPtr(), nn, acc); return;	// LD (nn),A
			case 0x3A: Output("\t%sA = Read8(%s, 0x%04X);\n", acc, CpuPtr(), nn); return;	// LD A,(nn)
			}
		}
	}

	if (x == 3)
	{
		static const char* kHi[4] = { "B", "D", "H", "A" };	// PUSH/POP pair high byte
		static const char* kLo[4] = { "C", "E", "L", "F" };	// ... low byte (AF = A:F)

		if (z == 1 && q == 0)	// POP qq
		{
			Output("\t%s%s = Read8(%s, %sSP); %s%s = Read8(%s, %sSP+1); %sSP += 2;\n",
				acc, kLo[p], CpuPtr(), acc, acc, kHi[p], CpuPtr(), acc, acc);
			return;
		}
		if (z == 5 && q == 0)	// PUSH qq
		{
			Output("\t%sSP -= 2; Write8(%s, %sSP+1, %s%s); Write8(%s, %sSP, %s%s);\n",
				acc, CpuPtr(), acc, acc, kHi[p], CpuPtr(), acc, acc, kLo[p]);
			return;
		}
		if (z == 1 && q == 1)	// EXX (0xD9) / LD SP,HL (0xF9); RET / JP(HL) are terminators
		{
			if (op == 0xD9) { Output("\tz80_exx(%s);\n", CpuPtr()); return; }
			if (op == 0xF9) { Output("\t%sSP = z80_hl(%s);\n", acc, CpuPtr()); return; }
		}
		if (z == 3)	// OUT/IN/EX/DI/EI (the z==3 control-flow forms are terminators)
		{
			const uint8_t n = state.ReadByte(addr.Address + 1);
			switch (op)
			{
			case 0xD3: Output("\tOut(%s, (%sA<<8)|0x%02X, %sA);\n", CpuPtr(), acc, n, acc); return;	// OUT (n),A
			case 0xDB: Output("\t%sA = In(%s, (%sA<<8)|0x%02X);\n", acc, CpuPtr(), acc, n); return;	// IN A,(n)
			case 0xEB: Output("\tz80_ex_de_hl(%s);\n", CpuPtr()); return;	// EX DE,HL
			case 0xF3: Output("\t%sIFF1 = %sIFF2 = false;\n", acc, acc); return;	// DI
			case 0xFB: Output("\t%sIFF1 = %sIFF2 = true;\n", acc, acc); return;	// EI
			case 0xE3:	// EX (SP),HL
				Output("\t{ uint8_t lo = Read8(%s, %sSP), hi = Read8(%s, %sSP+1);\n", CpuPtr(), acc, CpuPtr(), acc);
				Output("\t  Write8(%s, %sSP, %sL); Write8(%s, %sSP+1, %sH); %sL = lo; %sH = hi; }\n",
					CpuPtr(), acc, acc, CpuPtr(), acc, acc, acc, acc);
				return;
			}
		}
	}

	if (op == 0xED)
	{
		EmitInstructionSemanticsZ80_ED(addr);
		return;
	}

	// Outside this batch (DD/FD-prefixed instructions etc.).
	Output("\t/* TODO(Phase 1): semantics for opcode 0x%02X */\n", op);
}

// ED-prefixed opcodes: extended set covering NEG, IM, LD I/R/A swaps, ADC/SBC HL, 16-bit
// LD (nn),rp / LD rp,(nn), IN r,(C) / OUT (C),r, RRD/RLD, and the block ops with their
// repeating variants. RETI/RETN are flow-terminators and don't reach here. NOP-like and
// duplicate-NEG / duplicate-IM encodings (the documented Z80 has eight NEGs, four IM 0s
// etc.) are emitted as their primary form. Reference: z80.info/decoding.htm, ED page.
void FCppExporter::EmitInstructionSemanticsZ80_ED(FAddressRef addr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const uint8_t op2 = state.ReadByte(addr.Address + 1);
	const int x = op2 >> 6, y = (op2 >> 3) & 7, z = op2 & 7;
	const int p = y >> 1, q = y & 1;
	const char* acc = Acc();

	static const char* kReg[8] = { "B", "C", "D", "E", "H", "L", "(HL)", "A" };
	static const char* kRp[4]  = { "bc", "de", "hl", "sp" };	// rp[3] handled as direct SP access

	auto rpRead = [&](int pp) -> std::string {
		char buf[32];
		if (pp == 3) { snprintf(buf, sizeof(buf), "%sSP", acc); return buf; }
		snprintf(buf, sizeof(buf), "z80_%s(%s)", kRp[pp], CpuPtr());
		return buf;
	};
	auto rpWrite = [&](int pp, const std::string& expr) {
		if (pp == 3) { Output("\t%sSP = %s;\n", acc, expr.c_str()); return; }
		Output("\tz80_set_%s(%s, %s);\n", kRp[pp], CpuPtr(), expr.c_str());
	};

	// ---- 0x40-0x7F: the "main" ED range ----
	if (x == 1)
	{
		const uint16_t nn = state.ReadWord(addr.Address + 2);

		if (z == 0)	// IN r,(C)  (r=6 -> IN F,(C): flags only, no destination)
		{
			Output("\t{ uint8_t v = In(%s, z80_bc(%s)); z80_in_flags(%s, v);",
				CpuPtr(), CpuPtr(), CpuPtr());
			if (y != 6)
				Output(" %s%s = v;", acc, kReg[y]);
			Output(" }\n");
			return;
		}
		if (z == 1)	// OUT (C),r  (r=6 -> OUT (C),0  on most Z80s)
		{
			if (y == 6)
				Output("\tOut(%s, z80_bc(%s), 0);\n", CpuPtr(), CpuPtr());
			else
				Output("\tOut(%s, z80_bc(%s), %s%s);\n", CpuPtr(), CpuPtr(), acc, kReg[y]);
			return;
		}
		if (z == 2)	// SBC HL,rp (q==0) / ADC HL,rp (q==1)
		{
			Output("\t%s(%s, %s);\n", q ? "z80_adc16" : "z80_sbc16", CpuPtr(), rpRead(p).c_str());
			return;
		}
		if (z == 3)	// LD (nn),rp (q==0) / LD rp,(nn) (q==1)
		{
			if (q == 0)
			{
				if (p == 3)	// SP
				{
					Output("\tWrite8(%s, 0x%04X, (uint8_t)%sSP); Write8(%s, 0x%04X, (uint8_t)(%sSP>>8));\n",
						CpuPtr(), nn, acc, CpuPtr(), (uint16_t)(nn + 1), acc);
				}
				else
				{
					static const char* lo[3] = { "C", "E", "L" };
					static const char* hi[3] = { "B", "D", "H" };
					Output("\tWrite8(%s, 0x%04X, %s%s); Write8(%s, 0x%04X, %s%s);\n",
						CpuPtr(), nn, acc, lo[p], CpuPtr(), (uint16_t)(nn + 1), acc, hi[p]);
				}
			}
			else
			{
				if (p == 3)
				{
					Output("\t%sSP = (uint16_t)(Read8(%s, 0x%04X) | (Read8(%s, 0x%04X) << 8));\n",
						acc, CpuPtr(), nn, CpuPtr(), (uint16_t)(nn + 1));
				}
				else
				{
					static const char* lo[3] = { "C", "E", "L" };
					static const char* hi[3] = { "B", "D", "H" };
					Output("\t%s%s = Read8(%s, 0x%04X); %s%s = Read8(%s, 0x%04X);\n",
						acc, lo[p], CpuPtr(), nn, acc, hi[p], CpuPtr(), (uint16_t)(nn + 1));
				}
			}
			return;
		}
		if (z == 4) { Output("\tz80_neg(%s);\n", CpuPtr()); return; }	// NEG (and dup encodings)
		// z == 5: RETI/RETN handled as terminator (bEndsBlock); never reaches here.
		if (z == 6)	// IM n. y -> mode: 0,0,1,2,0,0,1,2.
		{
			static const uint8_t kImTable[8] = { 0, 0, 1, 2, 0, 0, 1, 2 };
			Output("\t%sIM = %u;\n", acc, kImTable[y]);
			return;
		}
		if (z == 7)	// LD I,A; LD R,A; LD A,I; LD A,R; RRD; RLD; NOP; NOP
		{
			switch (y)
			{
			case 0: Output("\t%sI = %sA;\n", acc, acc); return;
			case 1: Output("\t%sR = %sA;\n", acc, acc); return;
			case 2: // LD A,I - sets flags from I (sz + PV=IFF2), CF preserved, NF/HF cleared
				Output("\t%sA = %sI; %sF = (%sF & Z80_CF) | z80_sz(%sA) | (%sA & (Z80_YF|Z80_XF)) | (%sIFF2 ? Z80_PF : 0);\n",
					acc, acc, acc, acc, acc, acc, acc);
				return;
			case 3: // LD A,R - same flag effects as LD A,I
				Output("\t%sA = %sR; %sF = (%sF & Z80_CF) | z80_sz(%sA) | (%sA & (Z80_YF|Z80_XF)) | (%sIFF2 ? Z80_PF : 0);\n",
					acc, acc, acc, acc, acc, acc, acc);
				return;
			case 4: // RRD
				Output("\t{ uint16_t hl = (%sH<<8)|%sL; Write8(%s, hl, z80_rrd(%s, Read8(%s, hl))); }\n",
					acc, acc, CpuPtr(), CpuPtr(), CpuPtr());
				return;
			case 5: // RLD
				Output("\t{ uint16_t hl = (%sH<<8)|%sL; Write8(%s, hl, z80_rld(%s, Read8(%s, hl))); }\n",
					acc, acc, CpuPtr(), CpuPtr(), CpuPtr());
				return;
			case 6: case 7: Output("\t/* ED NOP (y=%d) */\n", y); return;
			}
		}
	}

	// ---- 0xA0-0xBF: block ops ----
	// y = 4 inc/single, 5 dec/single, 6 inc/repeat, 7 dec/repeat. z selects family.
	if (x == 2 && y >= 4 && z <= 3)
	{
		const bool bDec    = (y & 1) != 0;
		const bool bRepeat = (y & 2) != 0;
		const char* hlStep = bDec ? "-1" : "+1";

		// For repeating variants we emit `do { ... } while (helper(...))`. The block-local
		// `v` (byte just transferred / compared / I/O'd) must be visible to the while
		// condition, so we declare it in the enclosing scope rather than inside the do-block.
		if (z == 0)	// LDI / LDD / LDIR / LDDR
		{
			Output("\t{ uint8_t v; uint16_t hl, de;\n");
			Output("\t  %s{ hl=z80_hl(%s); de=z80_de(%s); v=Read8(%s, hl); Write8(%s, de, v);\n",
				bRepeat ? "do " : "", CpuPtr(), CpuPtr(), CpuPtr(), CpuPtr());
			Output("\t    z80_set_hl(%s, (uint16_t)(hl%s)); z80_set_de(%s, (uint16_t)(de%s));\n",
				CpuPtr(), hlStep, CpuPtr(), hlStep);
			if (bRepeat)
				Output("\t  } while (z80_ldi_ldd(%s, v)); }\n", CpuPtr());
			else
				Output("\t    z80_ldi_ldd(%s, v); } }\n", CpuPtr());
			return;
		}
		if (z == 1)	// CPI / CPD / CPIR / CPDR
		{
			Output("\t{ uint8_t v; uint16_t hl;\n");
			Output("\t  %s{ hl=z80_hl(%s); v=Read8(%s, hl); z80_set_hl(%s, (uint16_t)(hl%s));\n",
				bRepeat ? "do " : "", CpuPtr(), CpuPtr(), CpuPtr(), hlStep);
			if (bRepeat)
				Output("\t  } while (z80_cpi_cpd(%s, v)); }\n", CpuPtr());
			else
				Output("\t    z80_cpi_cpd(%s, v); } }\n", CpuPtr());
			return;
		}
		if (z == 2)	// INI / IND / INIR / INDR
		{
			Output("\t{ uint8_t v; uint16_t hl;\n");
			Output("\t  %s{ hl=z80_hl(%s); v=In(%s, z80_bc(%s)); %sB--;\n",
				bRepeat ? "do " : "", CpuPtr(), CpuPtr(), CpuPtr(), acc);
			Output("\t    Write8(%s, hl, v); z80_set_hl(%s, (uint16_t)(hl%s));\n",
				CpuPtr(), CpuPtr(), hlStep);
			// chips passes C+/-1 as the helper's `c` arg (matches the WZ-based parity hack).
			if (bRepeat)
				Output("\t  } while (z80_ini_ind(%s, v, (uint8_t)(%sC%s))); }\n", CpuPtr(), acc, hlStep);
			else
				Output("\t    z80_ini_ind(%s, v, (uint8_t)(%sC%s)); } }\n", CpuPtr(), acc, hlStep);
			return;
		}
		if (z == 3)	// OUTI / OUTD / OTIR / OTDR
		{
			Output("\t{ uint8_t v; uint16_t hl;\n");
			Output("\t  %s{ hl=z80_hl(%s); v=Read8(%s, hl); %sB--;\n",
				bRepeat ? "do " : "", CpuPtr(), CpuPtr(), acc);
			Output("\t    Out(%s, z80_bc(%s), v); z80_set_hl(%s, (uint16_t)(hl%s));\n",
				CpuPtr(), CpuPtr(), CpuPtr(), hlStep);
			if (bRepeat)
				Output("\t  } while (z80_outi_outd(%s, v)); }\n", CpuPtr());
			else
				Output("\t    z80_outi_outd(%s, v); } }\n", CpuPtr());
			return;
		}
	}

	// Undocumented / "invalid" ED-prefix opcodes act as 2-byte NOPs on the original Z80.
	Output("\t/* ED 0x%02X: undocumented / acts as NOP */\n", op2);
}

std::string FCppExporter::ConditionExpr(FAddressRef addr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const uint8_t op = state.ReadByte(addr);
	const char* acc = Acc();
	char buf[64];

	if (op == 0x10)	// DJNZ: decrement B and branch if non-zero (does not touch flags)
	{
		snprintf(buf, sizeof(buf), "(--%sB != 0)", acc);
		return buf;
	}

	// Condition code: JR cc,d encodes it in bits 4..3 (NZ,Z,NC,C); JP/CALL/RET cc use bits 5..3.
	int cc;
	if (op == 0x20 || op == 0x28 || op == 0x30 || op == 0x38)
		cc = (op >> 3) & 3;
	else
		cc = (op >> 3) & 7;

	static const char* kFlag[8] = { "Z80_ZF", "Z80_ZF", "Z80_CF", "Z80_CF",
	                                "Z80_PF", "Z80_PF", "Z80_SF", "Z80_SF" };
	const bool bFlagSet = (cc & 1) != 0;	// odd cc tests "flag set", even tests "flag clear"
	snprintf(buf, sizeof(buf), "%s(%sF & %s)", bFlagSet ? "" : "!", acc, kFlag[cc]);
	return buf;
}

void FCppExporter::EmitTerminator(const FBasicBlock& block)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FInstructionFlow flow = ClassifyInstruction(state, block.LastInstruction);

	// Every transfer is "set PC, return to the dispatcher". A target outside the
	// translated code simply leaves PC there and z80_run stops (lookup fails).
	const uint16_t nextAddr = (uint16_t)(block.LastInstruction.Address + flow.ByteSize);
	const uint16_t target   = flow.Target.Address;
	const std::string cond  = ConditionExpr(block.LastInstruction);

	switch (block.Terminator)
	{
		case EBlockTerminator::FallThrough:
			Output("\tcpu->PC = 0x%04X; return;\n", nextAddr);
			break;

		case EBlockTerminator::UncondBranch:
			Output("\tcpu->PC = 0x%04X; return;\n", target);
			break;

		case EBlockTerminator::CondBranch:
			Output("\tif (%s) { cpu->PC = 0x%04X; return; }\n", cond.c_str(), target);
			Output("\tcpu->PC = 0x%04X; return;\n", nextAddr);
			break;

		case EBlockTerminator::Call:
			if (flow.bConditional)
			{
				Output("\tif (%s) { z80_push16(cpu, 0x%04X); cpu->PC = 0x%04X; return; }\n", cond.c_str(), nextAddr, target);
				Output("\tcpu->PC = 0x%04X; return;\n", nextAddr);
			}
			else
			{
				Output("\tz80_push16(cpu, 0x%04X); cpu->PC = 0x%04X; return;\n", nextAddr, target);
			}
			break;

		case EBlockTerminator::Return:
			if (flow.bConditional)
			{
				Output("\tif (%s) { cpu->PC = z80_pop16(cpu); return; }\n", cond.c_str());
				Output("\tcpu->PC = 0x%04X; return;\n", nextAddr);
			}
			else
			{
				Output("\tcpu->PC = z80_pop16(cpu); return;\n");
			}
			break;

		case EBlockTerminator::IndirectJump:
			// JP (HL) (unprefixed 0xE9). The DD/FD (IX/IY) variants are a later page.
			Output("\tcpu->PC = z80_hl(cpu); return;   // JP (HL)\n");
			break;

		case EBlockTerminator::Halt:
			Output("\tcpu->Halted = true; return;\n");
			break;

		default:
			Output("\tcpu->PC = 0x%04X; return;\n", nextAddr);
			break;
	}
}

void FCppExporter::EmitBasicBlock(const FBasicBlock& block)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();

	Output("static void %s(Z80CpuState* cpu)   // 0x%04X .. 0x%04X%s%s\n{\n",
		BlockLabel(block.StartAddress).c_str(),
		block.StartAddress.Address, block.EndAddress.Address,
		block.bIsEntry ? "  [entry]" : "",
		block.bContainsSelfModifyingCode ? "  [SMC]" : "");

	if (block.bContainsSelfModifyingCode)
		Output("\t// NOTE: self-modifying code in this block - route through fallback interpreter (later).\n");

	// Emit each instruction in the block in address order.
	FAddressRef addr = block.StartAddress;
	while (addr.IsValid() && addr <= block.LastInstruction)
	{
		const FCodeInfo* pCodeInfo = state.GetCodeInfoForAddress(addr);
		const uint16_t byteSize = (pCodeInfo != nullptr && pCodeInfo->ByteSize > 0) ? pCodeInfo->ByteSize : 1;

		EmitInstruction(addr);

		if (state.AdvanceAddressRef(addr, byteSize) == false)
			break;
	}

	EmitTerminator(block);
	Output("}\n\n");
}

// -------------------------------------------------------------------------------------
// Top-level program emission
// -------------------------------------------------------------------------------------

bool FCppExporter::ExportProgram(uint16_t startAddr, uint16_t endAddr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();

	const FAddressRef start = state.AddressRefFromPhysicalAddress(startAddr);
	const FAddressRef end   = state.AddressRefFromPhysicalAddress(endAddr);

	if (BuildCFGForAddressRange(state, start, end, CFG) == false)
		return false;

	// Entry-point list (informational) in the header now that the CFG exists.
	SetOutputToHeader();
	EmitEntryPointDeclarations();

	SetOutputToBody();
	Output("// ---- Translated blocks (one function per basic block) ------------------\n\n");

	for (const auto& blockPair : CFG.Blocks)	// std::map => address order
		EmitBasicBlock(blockPair.second);

	EmitDispatcher();

	if (RecompilerConfig.bEmitHarness)
		EmitHarness();

	return true;
}

// The PC-dispatch execution engine: a PC->block-function table and the run loop. Control
// transfers in block bodies just set cpu->PC and return here; CALL/RET push/pop the return
// PC on the Z80 stack, so calls, returns and computed jumps all resolve through the loop.
// When PC lands on an address with no block (e.g. RET to the caller, or a jump out of the
// translated range) z80_run stops, leaving cpu->PC for the caller to inspect.
void FCppExporter::EmitDispatcher(void)
{
	Output("// ---- PC-dispatch engine ------------------------------------------------\n");
	Output("typedef void (*Z80BlockFn)(Z80CpuState*);\n\n");

	Output("static Z80BlockFn z80_lookup(uint16_t pc)\n{\n\tswitch (pc)\n\t{\n");
	for (const auto& blockPair : CFG.Blocks)
		Output("\tcase 0x%04X: return %s;\n", blockPair.first.Address, BlockLabel(blockPair.first).c_str());
	Output("\tdefault: return 0;\n\t}\n}\n\n");

	Output("void z80_run(Z80CpuState* cpu)\n{\n");
	Output("\twhile (!cpu->Halted)\n\t{\n");
	Output("\t\tZ80BlockFn fn = z80_lookup(cpu->PC);\n");
	Output("\t\tif (!fn) return;   // PC left the translated code\n");
	Output("\t\tfn(cpu);\n\t}\n}\n\n");

	Output("// Enter a routine: push a sentinel return address (unmapped, so the routine's\n");
	Output("// final RET stops z80_run), set PC, and run.\n");
	Output("void z80_call(Z80CpuState* cpu, uint16_t entry)\n{\n");
	Output("\tz80_push16(cpu, 0xFFFF);\n\tcpu->PC = entry;\n\tz80_run(cpu);\n}\n");
}

// Self-contained runtime so a generated translation unit compiles and runs standalone:
// a flat 64K memory and the Read8/Write8/In/Out hooks declared in the header. With the
// PC-dispatch engine this runs full routines (calls/returns/computed jumps) - drive it via
// z80_call(cpu, entry). Customise the memory map and IO for a real target.
void FCppExporter::EmitHarness(void)
{
	Output("\n// ---- Minimal runtime harness (memory + IO) -----------------------------\n");
	Output("static uint8_t g_Z80Mem[0x10000];\n\n");
	Output("uint8_t Read8 (Z80CpuState* cpu, uint16_t addr){ (void)cpu; return g_Z80Mem[addr]; }\n");
	Output("void    Write8(Z80CpuState* cpu, uint16_t addr, uint8_t val){ (void)cpu; g_Z80Mem[addr] = val; }\n");
	Output("uint8_t In    (Z80CpuState* cpu, uint16_t port){ (void)cpu; (void)port; return 0xFF; }\n");
	Output("void    Out   (Z80CpuState* cpu, uint16_t port, uint8_t val){ (void)cpu; (void)port; (void)val; }\n");
}

// -------------------------------------------------------------------------------------
// Free entry point (mirrors ExportAssembler)
// -------------------------------------------------------------------------------------

bool ExportCpp(FEmuBase* pEmu, const char* pFilename, uint16_t startAddr, uint16_t endAddr, bool bEmitC, bool bEmitHarness)
{
	FCppExporter exporter;
	if (exporter.Init(pFilename, pEmu) == false)
		return false;

	exporter.SetTargetLanguageC(bEmitC);	// must precede AddHeader (it emits language-specific preamble)
	exporter.SetEmitHarness(bEmitHarness);
	exporter.SetOutputToHeader();
	exporter.AddHeader();

	const bool bSuccess = exporter.ExportProgram(startAddr, endAddr);

	exporter.Finish();
	return bSuccess;
}
