#include "CppExporter.h"

#include "CodeAnalyser/CodeAnalyser.h"
#include "CodeAnalyser/FunctionAnalyser.h"
#include "Misc/EmuBase.h"

#include <stdio.h>

// =====================================================================================
// Tier-A C++ recompiler backend (SKELETON). See CppExporter.h header comment.
//
// Control-flow model: one big translation function per program, basic blocks emitted as
// goto-labelled sections in address order. This handles overlapping / fall-through entry
// points (e.g. AddAToHL* at $AEE3/4/5) for free, because every entry is just a label.
// =====================================================================================

// -------------------------------------------------------------------------------------
// Naming helpers
// -------------------------------------------------------------------------------------

std::string FCppExporter::BlockLabel(FAddressRef addr) const
{
	char buf[32];
	snprintf(buf, sizeof(buf), "L_%04X", addr.Address);
	return buf;
}

std::string FCppExporter::FunctionName(FAddressRef addr) const
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FLabelInfo* pLabel = state.GetLabelForAddress(addr);
	if (pLabel != nullptr && pLabel->GetName()[0] != '\0')
		return pLabel->GetName();

	char buf[32];
	snprintf(buf, sizeof(buf), "func_%04X", addr.Address);
	return buf;
}

std::string FCppExporter::DisassemblyText(FAddressRef addr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FCodeInfo* pCodeInfo = state.GetCodeInfoForAddress(addr);
	if (pCodeInfo != nullptr && pCodeInfo->Text.empty() == false)
		return pCodeInfo->Text;	// stored disassembly; good enough for a provenance comment
	return "<no disassembly>";
}

// -------------------------------------------------------------------------------------
// Runtime preamble (header)
// -------------------------------------------------------------------------------------

void FCppExporter::EmitCpuStateStruct(void)
{
	const bool bC = RecompilerConfig.bEmitC;
	Output("// ---- CPU state ---------------------------------------------------------\n");
	Output(bC ? "typedef struct\n{\n" : "struct Z80CpuState\n{\n");
	Output("\tuint8_t  A, F, B, C, D, E, H, L;\n");
	Output("\tuint8_t  A_, F_, B_, C_, D_, E_, H_, L_;   // shadow registers\n");
	Output("\tuint16_t IX, IY, SP, PC;\n");
	Output("\tuint8_t  I, R;\n");
	Output("\tbool     IFF1, IFF2;\n");
	Output("\tuint8_t  IM;\n");
	Output("\tbool     Halted;\n");
	Output("\tuint64_t Cycles;          // for timing-sensitive code / IRQ gating\n");
	Output("\tuint8_t* Mem;             // 64K (or paging-window) byte array, AUTHORITATIVE\n");
	Output(bC ? "} Z80CpuState;\n\n" : "};\n\n");
}

void FCppExporter::EmitRuntimeDeclarations(void)
{
	const char* pCpu = CpuArgDecl();
	Output("// ---- Runtime hooks (provided by the harness) ---------------------------\n");
	Output("// Memory is the authoritative source of truth so that self-modifying code,\n");
	Output("// banking and I/O all remain interception points rather than special cases.\n");
	Output("uint8_t  Read8 (%s, uint16_t addr);\n", pCpu);
	Output("void     Write8(%s, uint16_t addr, uint8_t val);\n", pCpu);
	Output("uint8_t  In    (%s, uint16_t port);\n", pCpu);
	Output("void     Out   (%s, uint16_t port, uint8_t val);\n\n", pCpu);
	Output("// Control-flow helpers. Call/JumpTo/DispatchIndirect look up an address->handler\n");
	Output("// map; unresolved indirect targets (jump tables) route through DispatchIndirect.\n");
	Output("void     Call           (%s, uint16_t target);\n", pCpu);
	Output("void     JumpTo         (%s, uint16_t target);\n", pCpu);
	Output("void     DispatchIndirect(%s, uint16_t target);\n\n", pCpu);
}

void FCppExporter::EmitEntryPointDeclarations(void)
{
	Output("// ---- Entry points ------------------------------------------------------\n");
	for (const FAddressRef& entry : CFG.EntryPoints)
		Output("void %s(%s);   // 0x%04X\n", FunctionName(entry).c_str(), CpuArgDecl(), entry.Address);
	Output("\n");
}

void FCppExporter::AddHeader(void)
{
	Output("// Machine-generated by 8BitAnalysers FCppExporter (Tier A - faithful translation).\n");
	Output("// Target: %s. DO NOT EDIT: regenerate from the analysis project instead.\n\n",
		RecompilerConfig.bEmitC ? "C99" : "C++");
	if (RecompilerConfig.bEmitC)
		Output("#include <stdint.h>\n#include <stdbool.h>\n\n");
	else
		Output("#include <cstdint>\n\n");
	EmitCpuStateStruct();
	EmitRuntimeDeclarations();
	// Entry-point declarations depend on the CFG, which is built in ExportProgram;
	// they are appended there once CFG.EntryPoints is populated.
}

// -------------------------------------------------------------------------------------
// Instruction & block emission
// -------------------------------------------------------------------------------------

void FCppExporter::EmitInstruction(FAddressRef addr, bool bIsTerminator)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();
	const FInstructionFlow flow = ClassifyInstruction(state, addr);

	// Provenance comment - always emitted so the generated code stays auditable.
	Output("\t// %04X: %s\n", addr.Address, DisassemblyText(addr).c_str());

	// Calls happen mid-block and must be emitted in stream order.
	if (flow.bIsCall && flow.Target.IsValid())
	{
		if (flow.bConditional)
			Output("\tif (/* TODO(Phase 1): call condition */ true) Call(cpu, 0x%04X); // %s\n",
				flow.Target.Address, FunctionName(flow.Target).c_str());
		else
			Output("\tCall(cpu, 0x%04X); // %s\n", flow.Target.Address, FunctionName(flow.Target).c_str());
		return;
	}

	// The terminator's control transfer is emitted by EmitTerminator, not here.
	if (bIsTerminator)
		return;

	// TODO(Phase 1): replace this stub with the opcode's real C++ semantics.
	// The semantics table (register/flag/memory effects) is generated from / validated
	// against Source/Vendor/chips/z80.h. Memory touches must go through Read8/Write8.
	Output("\t/* TODO(Phase 1): semantics */\n");
}

void FCppExporter::EmitTerminator(const FBasicBlock& block)
{
	auto findSuccessor = [&](EEdgeType type) -> const FFlowEdge*
	{
		for (const FFlowEdge& e : block.Successors)
			if (e.Type == type)
				return &e;
		return nullptr;
	};

	auto emitGotoOrJump = [&](FAddressRef target)
	{
		if (CFG.GetBlockStartingAt(target) != nullptr)
			Output("\tgoto %s;\n", BlockLabel(target).c_str());	// stays inside this TU
		else
			Output("\tJumpTo(cpu, 0x%04X); return;   // target outside translated range\n", target.Address);
	};

	switch (block.Terminator)
	{
		case EBlockTerminator::FallThrough:
		{
			const FFlowEdge* pEdge = findSuccessor(EEdgeType::FallThrough);
			if (pEdge != nullptr)
				emitGotoOrJump(pEdge->To);
			else
				Output("\treturn;   // falls off translated range\n");	// keep the label statement-terminated
			break;
		}
		case EBlockTerminator::UncondBranch:
		{
			const FFlowEdge* pEdge = findSuccessor(EEdgeType::Jump);
			if (pEdge != nullptr)
				emitGotoOrJump(pEdge->To);
			else
				Output("\tDispatchIndirect(cpu, %sPC); return;   // unresolved jump\n", Acc());
			break;
		}
		case EBlockTerminator::CondBranch:
		{
			const FFlowEdge* pBranch = findSuccessor(EEdgeType::Branch);
			const FFlowEdge* pFall   = findSuccessor(EEdgeType::FallThrough);
			if (pBranch != nullptr)
			{
				// TODO(Phase 1/2): emit the real flag predicate (Z/C/PO/...) or, where the
				// flag's only consumer is this branch, lift to a direct comparison (Phase 2).
				Output("\tif (/* TODO(Phase 1): branch condition */ false) goto %s;\n",
					BlockLabel(pBranch->To).c_str());
			}
			if (pFall != nullptr)
				emitGotoOrJump(pFall->To);
			break;
		}
		case EBlockTerminator::Return:
		{
			// A fall-through successor exists iff this was a *conditional* RET.
			const FFlowEdge* pFall = findSuccessor(EEdgeType::FallThrough);
			if (pFall != nullptr)
			{
				Output("\tif (/* TODO(Phase 1): return condition */ false) return;\n");
				emitGotoOrJump(pFall->To);
			}
			else
			{
				Output("\treturn;\n");
			}
			break;
		}
		case EBlockTerminator::IndirectJump:
			// TODO(Phase 0 pass 4 / Phase 1): pass the real index register (HL/IX/IY).
			Output("\tDispatchIndirect(cpu, /* TODO: index reg */ %sPC); return;\n", Acc());
			break;
		case EBlockTerminator::Halt:
			Output("\t%sHalted = true; return;\n", Acc());
			break;
		default:
			break;
	}
}

void FCppExporter::EmitBasicBlock(const FBasicBlock& block)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();

	Output("%s:   // 0x%04X .. 0x%04X%s%s\n",
		BlockLabel(block.StartAddress).c_str(),
		block.StartAddress.Address, block.EndAddress.Address,
		block.bIsEntry ? "  [entry]" : "",
		block.bContainsSelfModifyingCode ? "  [SMC]" : "");

	if (block.bContainsSelfModifyingCode)
		Output("\t// NOTE: self-modifying code in this block - route through fallback interpreter (Phase 1).\n");

	// Emit each instruction in the block in address order.
	FAddressRef addr = block.StartAddress;
	while (addr.IsValid() && addr <= block.LastInstruction)
	{
		const FCodeInfo* pCodeInfo = state.GetCodeInfoForAddress(addr);
		const uint16_t byteSize = (pCodeInfo != nullptr && pCodeInfo->ByteSize > 0) ? pCodeInfo->ByteSize : 1;
		const bool bIsTerminator = (addr == block.LastInstruction);

		EmitInstruction(addr, bIsTerminator);

		if (state.AdvanceAddressRef(addr, byteSize) == false)
			break;
	}

	EmitTerminator(block);
	Output("\n");
}

// -------------------------------------------------------------------------------------
// Top-level program emission
// -------------------------------------------------------------------------------------

bool FCppExporter::ExportProgram(uint16_t startAddr, uint16_t endAddr)
{
	FCodeAnalysisState& state = pEmulator->GetCodeAnalysis();

	const FAddressRef start = state.AddressRefFromPhysicalAddress(startAddr);
	const FAddressRef end   = state.AddressRefFromPhysicalAddress(endAddr);

	if (BuildCFGForAddressRange(state, start, end, CFG) == false)
		return false;

	// Entry-point forward declarations now that the CFG exists.
	SetOutputToHeader();
	EmitEntryPointDeclarations();

	SetOutputToBody();
	Output("// ---- Translated code ---------------------------------------------------\n");

	// SKELETON: a single translation function with all blocks as goto labels. A later
	// milestone splits this per entry point (each entry becomes its own function whose
	// body is `goto L_<entry>;` into the shared label space, or its own block subset).
	Output("void Program_%04X(%s)\n{\n", startAddr, CpuArgDecl());

	for (const auto& blockPair : CFG.Blocks)	// std::map => address order
		EmitBasicBlock(blockPair.second);

	Output("}\n");

	// Report what still needs resolving so the user knows the output's limitations.
	if (CFG.UnresolvedEdges.empty() == false)
	{
		Output("\n// %zu unresolved indirect jump(s) - resolve via runtime traces or annotation:\n",
			CFG.UnresolvedEdges.size());
		for (const FFlowEdge& e : CFG.UnresolvedEdges)
			Output("//   from 0x%04X\n", e.From.Address);
	}

	return true;
}

// -------------------------------------------------------------------------------------
// Free entry point (mirrors ExportAssembler)
// -------------------------------------------------------------------------------------

bool ExportCpp(FEmuBase* pEmu, const char* pFilename, uint16_t startAddr, uint16_t endAddr, bool bEmitC)
{
	FCppExporter exporter;
	if (exporter.Init(pFilename, pEmu) == false)
		return false;

	exporter.SetTargetLanguageC(bEmitC);	// must precede AddHeader (it emits language-specific preamble)
	exporter.SetOutputToHeader();
	exporter.AddHeader();

	const bool bSuccess = exporter.ExportProgram(startAddr, endAddr);

	exporter.Finish();
	return bSuccess;
}
